language: python
services:
  - 
  # - go
  # - singularity
python:
  - "3.7"

# cache:
#   directories: 
#     - $HOME/.pip
#     # - $HOME/virtualenv ### too big
before_install: [] 
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a  
script:
  - set -e
  - |
    mkdir -p $HOME/bin
    export PATH=$PATH:$HOME/bin
    TAG=0.0.6
    # TAG=master  # for development branch
    curl -sL https://github.com/shouldsee/luck/archive/${TAG}.tar.gz -o luck-${TAG}.tar.gz
    tar -xvzf luck-${TAG}.tar.gz
    cd luck-${TAG}/
    install -m 755 bin/luck* $HOME/bin
    cd ..
  - luckmake -V ## to test accessibility
  - luckmake build
  - echo [DONE]
